### ISSUE TITLE
[Feature]: Tracking Issue - Explicit Tag 

### ISSUE THREAD

**Issue by d3rpp** [ciderapp/Fujisan-BugTracker#60]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11

### Describe the Bug

Songs that are marked as explicit do not have an "e" in the UI, this is typically required for compliance reasons

### Steps to Reproduce

launch Cider, go to a song with explicit content, notice the lack of E 

### Anything else?

I'm already building this, looks alright as of yet, just adding it so people know it's being worked on

**Comment by d3rpp** [comment]
Done
